#!/usr/bin/env bash
# Install nginx web server
apt update -y
apt install -y nginx
sudo chmod go+x /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
