#!/usr/bin/env bash
# Configure Nginx server for 301 redirect

sudo apt-get -y update
sudo apt-get install -y nginx
sudo chmod go+w /etc/nginx/sites-available/default
sudo touch /var/www/html/index.html
sudo chmod go+w /var/www/html/index.html

echo "server {
        listen 80;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html;
        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}" > /etc/nginx/sites-available/default
sudo service nginx restart
