#!/usr/bin/env bash
# This script displays "Best School" 10 times

myvar=1

while [ "$myvar" -le 10 ]
do
	echo "Best School"

	if [ "$myvar" = 9 ]
	then
		echo "Hi"
	fi

	myvar=$(( "$myvar" +1 ))
done
