#!/usr/bin/env bash
# This script  loops from 1 to 10 and: displays bad luck for the 4th loop iteration displays good luck for the 8th loop iteration displays Best School for the other iterations

myvar=1

while [ "$myvar" -le 10 ]
do
	if [ "$myvar" = 4 ]
	then
		echo "bad luck"
	elif [ "$myvar" = 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	
	myvar=$(( "$myvar" +1 ))
done
